languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
 exclude_paths:
   - "tests/*"
   - "database/*"
   - "config/*"
   - "public/*"
   - "resources/*"
   - "storage/*"
   - "vendor/*"
   - "bootstrap/*"
   - "tests/_support/_generated/ApiTesterActions.php"