language: php
php:
  - 5.6

before_script:
  - composer self-update
  - touch database/testing.sqlite
  - composer install -n --prefer-dist
  - php artisan migrate --database=sqlite_testing
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run -s acceptance --coverage-xml

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

after_script:
  - vendor/bin/test-reporter --coverage-report=tests/_output/coverage.xml --stdout > tests/_output/climate-coverage.json
  - "curl -X POST -d @tests/_output/climate-coverage.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.0.2)' https://codeclimate.com/test_reports"
