language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

script: phpunit --coverage-clover build/logs/clover.xml

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

install: composer install --no-interaction

cache:
  directories:
    - $HOME/.composer/cache

after_script:
  - vendor/bin/test-reporter --stdout > build/logs/coverage.json
  - "curl -X POST -d @build/logs/coverage.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.0.2)' https://codeclimate.com/test_reports"
